package com.legenda.lee.study_drools6

import com.legenda.lee.study_drools6.studydrools.fact.RuleEngineContext;
import com.legenda.lee.study_drools6.studydrools.util.CommonUtil;

rule rule_eventCode_packageId_ruleId_conditionId3
salience 1000
when
    $ruleEngineContext : RuleEngineContext(addressList contains "杭州");
then
    $ruleEngineContext.getOutputRiskFeatureKeyValue().put("output_feature_3", "通过");
    $ruleEngineContext.insertLog("自己组装3");
end

rule rule_eventCode_packageId_ruleId_conditionId4
salience 999
when
    $ruleEngineContext : RuleEngineContext(addressList not contains "上海");
then
    $ruleEngineContext.getOutputRiskFeatureKeyValue().put("output_feature_4", "通过");
    $ruleEngineContext.insertLog("自己组装4");
end

