package com.legenda.lee.study_drools6

import com.legenda.lee.study_drools6.studydrools.fact.RuleEngineContext;
import com.legenda.lee.study_drools6.studydrools.util.CommonUtil;

rule rule_eventCode_packageId_ruleId_conditionId3
salience 1000
when
    $ruleEngineContext : RuleEngineContext(inputRiskFeatureKeyValue.get("input_feature_xxx") <= 0.5 )
then
    $ruleEngineContext.getOutputRiskFeatureKeyValue().put("output_feature_xxx", "通过");
    $ruleEngineContext.insertLog("自己组装1");
end

rule rule_eventCode_packageId_ruleId_conditionId4
salience 999
when
    $ruleEngineContext : RuleEngineContext(CommonUtil.isContainsStr("连连Company", inputRiskFeatureKeyValue.get("input_feature_yyy")) )
then
    $ruleEngineContext.getOutputRiskFeatureKeyValue().put("output_feature_yyy", "通过");
    $ruleEngineContext.insertLog("自己组装2");
end

