package com.legenda.lee.study_drools6

import com.legenda.lee.study_drools6.studydrools.fact.RuleEngineContext;
import com.legenda.lee.study_drools6.studydrools.util.CommonUtil;

rule rule_eventCode_packageId_ruleId_conditionId5
salience 1000
when
    $ruleEngineContext : RuleEngineContext(inputRiskFeatureKeyValue.get("address1") memberOf addressList);
then
    $ruleEngineContext.getOutputRiskFeatureKeyValue().put("output_feature_5", "通过");
    $ruleEngineContext.insertLog("自己组装5");
end

rule rule_eventCode_packageId_ruleId_conditionId6
salience 999
when
    $ruleEngineContext : RuleEngineContext(inputRiskFeatureKeyValue.get("address1") not memberOf addressList);
then
    $ruleEngineContext.getOutputRiskFeatureKeyValue().put("output_feature_6", "通过");
    $ruleEngineContext.insertLog("自己组装6");
end

